In [1]:
from array import array

In [3]:
import numpy as np

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
a = np.array([[1, 2, 3],
[4, 5, 6]])

In [10]:
type(a)

numpy.ndarray

In [14]:
c = np.array([[0, 1, 2, 3, 4],
             [5, 6, 7, 8, 9],
             [10, 11, 12, 13, 14]])
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
type(b)

numpy.ndarray

In [17]:
b= np.arange(15)
b = b.reshape(3, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
b.ndim

2

In [21]:
b.dtype.name

'int32'

In [22]:
 2**32

4294967296

In [23]:
b.itemsize

4

In [24]:
b.size

15

In [25]:
b.shape

(3, 5)

## tworzenie tablic 

In [26]:
np.array([1, 2, 3])

array([1, 2, 3])

In [28]:
c = np.array([1.1, 2.2, 3.3])

In [29]:
c.dtype

dtype('float64')

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.ones((3, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [36]:
np.empty((3, 3))

array([[8.39911598e-323, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.16599492e-321],
       [3.09446630e+262, 3.90646695e+180, 5.99779942e+180]])

In [38]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
np.arange(60).reshape((4, 15))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [40]:
np.arange(10, 30 ,5)

array([10, 15, 20, 25])

In [41]:
np.linspace(0, 9 ,20)

array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,
       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,
       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,
       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])

In [42]:
a = np.arange(30).reshape(6, 5)

In [43]:
a*5

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145]])

In [44]:
b = a * 5

In [45]:
a - b

array([[   0,   -4,   -8,  -12,  -16],
       [ -20,  -24,  -28,  -32,  -36],
       [ -40,  -44,  -48,  -52,  -56],
       [ -60,  -64,  -68,  -72,  -76],
       [ -80,  -84,  -88,  -92,  -96],
       [-100, -104, -108, -112, -116]])

In [46]:
a / b

c:\users\kurs\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])

In [49]:
A = np.array([1, 1],
             [0, 1])
B = np.array([2, 0],
             [3, 4])

TypeError: data type not understood

In [48]:
b[2][2]

60

In [50]:
b[2 ,2]

60

In [51]:
b[1:3, 2:]

array([[35, 40, 45],
       [60, 65, 70]])