In [3]:
import numpy as np

In [5]:
np.random.seed(0)
arr = np.random.randint(-10,11,size=(10,10))
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9,   8,  -6],
       [ -4,   2,  -9,  -4,  -3,   4,   7,  -5,   3,  -2],
       [ -1,  10,   9,   6,   9,  -5,   5,   5, -10,   8],
       [ -7,   7,   9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10, -10,  -6],
       [ -5,  -4,  -2,  10,   7,   5,  -6,  -1,   0,  -9],
       [ -9,  -3,  -1,  -7,  -4,   1,   4,   8, -10,   4],
       [ -7,   2,   0,  10,   1,  -6,  -4,  -6,   5,  10],
       [ -7,   2,  -6,  10,  -2,   4,   5,  10,  -7,   5],
       [  3,   6,   7,  -5,  -1,  -7, -10,  -5, -10,   7]])

In [6]:
arr[0]

array([  2,   5, -10,  -7,  -7,  -3,  -1,   9,   8,  -6])

In [7]:
arr[0,2:4]

array([-10,  -7])

In [8]:
arr[:,::-1]

array([[ -6,   8,   9,  -1,  -3,  -7,  -7, -10,   5,   2],
       [ -2,   3,  -5,   7,   4,  -3,  -4,  -9,   2,  -4],
       [  8, -10,   5,   5,  -5,   9,   6,   9,  10,  -1],
       [ -1,  -9, -10,  -3,   4,   9,   9,   9,   7,  -7],
       [ -6, -10, -10,  -8,   8,   1,  -7,  10,   0, -10],
       [ -9,   0,  -1,  -6,   5,   7,  10,  -2,  -4,  -5],
       [  4, -10,   8,   4,   1,  -4,  -7,  -1,  -3,  -9],
       [ 10,   5,  -6,  -4,  -6,   1,  10,   0,   2,  -7],
       [  5,  -7,  10,   5,   4,  -2,  10,  -6,   2,  -7],
       [  7, -10,  -5, -10,  -7,  -1,  -5,   7,   6,   3]])

In [9]:
arr[:,-2:]

array([[  8,  -6],
       [  3,  -2],
       [-10,   8],
       [ -9,  -1],
       [-10,  -6],
       [  0,  -9],
       [-10,   4],
       [  5,  10],
       [ -7,   5],
       [-10,   7]])

In [11]:
arr[:5,[1,-2]]

array([[  5,   8],
       [  2,   3],
       [ 10, -10],
       [  7,  -9],
       [  0, -10]])

In [12]:
arr.shape

(10, 10)

In [13]:
for i in range(arr.shape[0]):
    print("="*50)
    print(arr[i])

[  2   5 -10  -7  -7  -3  -1   9   8  -6]
[-4  2 -9 -4 -3  4  7 -5  3 -2]
[ -1  10   9   6   9  -5   5   5 -10   8]
[ -7   7   9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10 -10  -6]
[-5 -4 -2 10  7  5 -6 -1  0 -9]
[ -9  -3  -1  -7  -4   1   4   8 -10   4]
[-7  2  0 10  1 -6 -4 -6  5 10]
[-7  2 -6 10 -2  4  5 10 -7  5]
[  3   6   7  -5  -1  -7 -10  -5 -10   7]


In [14]:
for row in arr:
    print("="*50)
    print(row)

[  2   5 -10  -7  -7  -3  -1   9   8  -6]
[-4  2 -9 -4 -3  4  7 -5  3 -2]
[ -1  10   9   6   9  -5   5   5 -10   8]
[ -7   7   9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10 -10  -6]
[-5 -4 -2 10  7  5 -6 -1  0 -9]
[ -9  -3  -1  -7  -4   1   4   8 -10   4]
[-7  2  0 10  1 -6 -4 -6  5 10]
[-7  2 -6 10 -2  4  5 10 -7  5]
[  3   6   7  -5  -1  -7 -10  -5 -10   7]


In [16]:
lista = range(1000)
%timeit -r 5 -n 1000 [i**2 for i in lista]

589 µs ± 18.4 µs per loop (mean ± std. dev. of 5 runs, 1000 loops each)


In [17]:
arr = np.arange(1000)
%timeit -r 5 -n 1000 arr**2

2.34 µs ± 284 ns per loop (mean ± std. dev. of 5 runs, 1000 loops each)
