In [1]:
import numpy as np

In [3]:
arr = np.array([2, 4, -3, 100, 33, 10])
arr

array([  2,   4,  -3, 100,  33,  10])

In [6]:
lista = list(arr)
[x for x in lista if x%2==0]


[2, 4, 100, 10]

In [7]:
arr%2==0

array([ True,  True, False,  True, False,  True])

In [8]:
arr[arr%2==0]

array([  2,   4, 100,  10])

In [9]:
arr=np.arange(-15,16)
arr

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
        -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
        11,  12,  13,  14,  15])

In [13]:
warunek = (arr<0) | (arr>10)
arr[warunek]

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
        -2,  -1,  11,  12,  13,  14,  15])

In [15]:
warunek = (arr>=0) & (arr<10)
arr[warunek]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr = np.array([-10, 1, np.nan, 4, 6, np.nan])
arr

array([-10.,   1.,  nan,   4.,   6.,  nan])

In [20]:
np.isnan(arr)

array([False, False,  True, False, False,  True])

In [21]:
arr[~np.isnan(arr)]

array([-10.,   1.,   4.,   6.])

In [22]:
np.isnan(arr).sum()

2

In [23]:
np.isnan(arr).any()

True

In [24]:
np.isnan(arr).all()

False